#!/bin/sh
#

FN="Source - Unique.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

. "$CMDDIR/../shared"

ytdlp_media "$FMTA" "$DNT/%(title).208s [%(id)s].%(ext)s" "--no-playlist"

"$CMDDIR/save_recent" "$PROXY"

"$CMDDIR/save_comments" "$PROXY"

write_html
