#!/bin/sh
#

FN="Source - Unique.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
. "$CMDDIR/../shared"

ytdlp_nonrecent_media "$DNT/%(title).208s [%(id)s].%(ext)s" --no-playlist
ytdlp_recent_media_with_comments "$DNT/%(title).208s [%(id)s].%(ext)s" --no-playlist
ytdlp_nonrecent_comments "$DNT/%(title).208s [%(id)s].comments.%(ext)s" --no-playlist
write_html
