#!/bin/sh
#

FN="Preview - Unique.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
. "$CMDDIR/../../shared"

ytdlp_preview "$DNT/%(title).208s [%(id)s].%(ext)s" --format-sort res~720 --no-playlist
ytdlp_all_comments "$DNT/%(title).208s [%(id)s].comments.%(ext)s" --no-playlist
write_html
