#!/bin/sh
#

FN="Preview - Unique.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

. "$CMDDIR/../../shared"

ytdlp_preview "$DNT/%(title).208s [%(id)s].%(ext)s" --format-sort res~720 --no-playlist

ytdlp_all_comments "$DNT/%(title).208s [%(id)s].comments.%(ext)s"

write_html

yt-dlp --no-playlist --format "$FMT" --format-sort "res~720" --verbose --force-ipv4 --sleep-requests 1 --sleep-interval 5 --max-sleep-interval 30 --ignore-errors --continue --no-overwrites --download-archive archive.log --add-metadata --write-description --write-info-json --write-annotations --write-thumbnail --embed-thumbnail --write-playlist-metafiles --write-url-link --get-comments --write-sub --write-auto-sub --sleep-subtitles 10 --sub-langs "en,en.*,ru,ru.*,de,de.*,live_chat" --match-filter "!is_live & !live" --output "$FNT" --merge-output-format "mp4" --no-check-certificate  --socket-timeout 10 --throttled-rate 50K --batch-file "$FN" 2>&1 | tee output.log
