#!/bin/sh
#

FN="Preview - Channels.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
. "$CMDDIR/../../shared"

ytdlp_preview "%(uploader)s/$DNT/%(title).208s [%(id)s].%(ext)s" --format-sort res~360
ytdlp_all_comments "%(uploader)s/$DNT/%(title).208s [%(id)s].comments.%(ext)s"
write_html
