#!/bin/sh
#

FN="Audio - Unique.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
. "$CMDDIR/../../shared"

ytdlp_audio "$DNT/%(title).208s [%(id)s].%(ext)s" --no-playlist
ytdlp_all_comments "$DNT/%(title).208s [%(id)s].comments.%(ext)s" --no-playlist
write_html
