#!/bin/sh
#

FN="Audio - Unique.txt"

if [ ! -s "$FN" ]; then
    echo "Sources should be specified in the '$FN' file\n in separated strings"
    exit
fi

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

yt-dlp --no-playlist --format "(bestaudio[acodec^=opus]/bestaudio)/best" --verbose --force-ipv4 --sleep-requests 1 --sleep-interval 5 --max-sleep-interval 30 --ignore-errors --no-continue --no-overwrites --download-archive archive.log --add-metadata --write-description --write-info-json --write-annotations --write-thumbnail --embed-thumbnail --write-playlist-metafiles --write-url-link --get-comments --write-sub --write-auto-sub --sleep-subtitles 10 --sub-langs "en,en.*,ru,ru.*,de,de.*,live_chat" --extract-audio --audio-quality 0 --match-filter "!is_live & !live" --output "%(title)s - %(uploader)s - %(upload_date)s/%(title)s - %(uploader)s - %(upload_date)s [%(id)s].%(ext)s" --no-check-certificate --socket-timeout 10 --throttled-rate 50K --batch-file "$FN" 2>&1 | tee output.log
"$CMDDIR/../../write_html"
