#!/bin/sh
#

FN="Source - Channels.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

. "$CMDDIR/../shared"

ytdlp_media "$FMTA" "%(uploader)s/$DNT/%(title).208s [%(id)s].%(ext)s"

"$CMDDIR/save_recent"

"$CMDDIR/save_comments"

write_html
