#!/bin/sh
#

FN="Source - Channels.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

. "$CMDDIR/../shared"

ytdlp_recent_media_with_comments "%(uploader)s/$DNT/%(title).208s [%(id)s].%(ext)s"

write_html
