#!/bin/sh
#

FN="Audio - Channels.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
. "$CMDDIR/../../shared"

ytdlp_audio "%(uploader)s/$DNT/%(title).208s [%(id)s].%(ext)s"
ytdlp_all_comments "%(uploader)s/$DNT/%(title).208s [%(id)s].comments.%(ext)s"
write_html
