#!/bin/sh

set -m

CMDDIR="$(cd "$(dirname "$0")" && pwd)"
PROXY="$1"

# Audio
"$CMDDIR/Audio/Unique/save" "$PROXY"
"$CMDDIR/Audio/Playlists/save" "$PROXY"
"$CMDDIR/Audio/Channels/save" "$PROXY"

# Preview
"$CMDDIR/Preview/Unique/save" "$PROXY"
"$CMDDIR/Preview/Playlists/save" "$PROXY"
"$CMDDIR/Preview/Channels/save" "$PROXY"

# Archivist
"$CMDDIR/Unique/save" "$PROXY"
"$CMDDIR/Playlists/save" "$PROXY"
"$CMDDIR/Channels/save" "$PROXY"

echo "Congratulations! All media were processed"
