#!/bin/sh

set -m

#TODO: support proxy

# Audio
cd Audio
cd Unique
./save
cd ..
cd Playlists
./save
cd ..
cd Channels
./save
cd ..
cd ..

# Preview
cd Preview
cd Unique
./save
cd ..
cd Playlists
./save
cd ..
cd Channels
./save
cd ..
cd ..

# Archivist
cd Unique
./save
cd ..
cd Playlists
./save
cd ..
cd Channels
./save
cd ..

echo "Done"
