#!/bin/sh

set -m

# Audio
cd Audio
cd Unique
./save
cd ..
cd Playlists
./save
cd ..
cd Channels
./save
cd ..
cd ..

# Archivist
cd Unique
./save
cd ..
cd Playlists
./save
cd ..
cd Channels
./save
cd ..

echo "Done"
