#!/bin/sh

wget_url() {
	FN1="$1"
	URL=""
	while IFS='= ' read var val
	do
		if [[ $var == \[*] ]]
		then
			section=$var
		elif [[ $val ]]
		then
			URL="$val"
			break
		fi
	done < "$FN1"
	if [[ $URL != "" ]]
	then
		FN2="${FN1%.url}.html"
		if [ ! -e "$FN2" ]
		then
			RNUMBER=$((RANDOM%10+1))
			echo "[html] Sleeping $RNUMBER.0 seconds ..."
			sleep $RNUMBER
			wget $URL --output-document="$FN2"
		fi
	fi
}

type -P wget &>/dev/null && ISINST=1 || ISINST=0
if [ $ISINST -eq 0 ]
then
	>&2 echo "Error: can't write html because of wget is not installed"
	return 127
fi

IFS=$'\n'
for I in `find . -name "*.url"`
do
	wget_url "$I"
done
