#!/bin/sh

wget_url() {
	FN1="$1"
	URL=$(cat "$FN1" | sed -n 2p)
	URL="${URL//[$'\t\r\n']}"
	URL="${URL#URL=}"
	if [[ $URL != "" ]]
	then
		local HASH=$(printf '%s' $URL | sha1sum 2>/dev/null | cut -d' ' -f1)
		if [[ "$HASH" == "" ]]; then
			HASH=$(printf '%s' $URL | openssl sha1 -r 2>/dev/null | cut -d' ' -f1)
			if [[ "$HASH" == "" ]]; then
				HASH=$(printf '%s' $URL | shasum -a 1 2>/dev/null | cut -d' ' -f1)
			fi
		fi
		if [[ "$HASH" != "" ]]; then
			HASH=" $HASH"
		fi
		FN2="${FN1%.url}$HASH.html"
		if [ ! -e "$FN2" ]
		then
			RNUMBER=$((RANDOM%10+1))
			echo "[html] Sleeping $RNUMBER.0 seconds ..."
			sleep $RNUMBER
			wget "$URL" --output-document="$FN2"
		fi
	fi
}

type -P wget &>/dev/null && ISINST=1 || ISINST=0
if [ $ISINST -eq 0 ]
then
	>&2 echo "Error: can't write html because of wget is not installed"
	return 127
fi

IFS=$'\n'
for I in `find . -name "*.url"`
do
	wget_url "$I"
done
