#!/bin/sh
#

FN="Source - Playlists.txt"

CMDDIR="$(cd "$(dirname "$0")" && pwd)"

. "$CMDDIR/../shared"

ytdlp_media "$FMTA" "%(playlist)s/$DNT/%(title).208s [%(id)s].%(ext)s"

"$CMDDIR/save_recent" "$PROXY"

"$CMDDIR/save_comments" "$PROXY"

write_html
